package view.extras;

import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import org.jdesktop.animation.timing.Animator;
import org.jdesktop.animation.timing.TimingTargetAdapter;



public class DialogoEntrada extends javax.swing.JDialog {

    private JFrame fram;
    private Animator animator;
    private Glass glass;
    private boolean show;    
    private String icone;
    private static String texto;
    
    public static final Icone ICONE_INFORMACAO = Icone.INFORMACAO;
    public static final Icone ICONE_SUCESSO = Icone.SUCESSO;
    public static final Icone ICONE_AVISO = Icone.AVISO;
    public static final Icone ICONE_QUESTAO = Icone.QUESTAO;
    public static final Icone ICONE_ERRO = Icone.ERRO;         
    
    private enum Icone {
        INFORMACAO, SUCESSO, AVISO, QUESTAO, ERRO
    }
    
    private DialogoEntrada(JFrame parent, Icone icone, String mensagem) {
        super(parent, true);
        fram = parent;
        init(icone);
        showMessage(mensagem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIcone = new javax.swing.JLabel();
        txt = new javax.swing.JTextPane();
        txtInput = new javax.swing.JTextField();
        botoes3 = new javax.swing.JPanel();
        btnCancelar1 = new view.extras.ButtonCustom();
        btnOk1 = new view.extras.ButtonCustom();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(344, 203));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(344, 203));
        jPanel1.setMinimumSize(new java.awt.Dimension(344, 203));
        jPanel1.setPreferredSize(new java.awt.Dimension(344, 203));

        lblIcone.setBackground(new java.awt.Color(255, 255, 255));
        lblIcone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/alerta.png"))); // NOI18N

        txt.setEditable(false);
        txt.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txt.setForeground(new java.awt.Color(76, 76, 76));
        txt.setText("Message Text\nSimple");
        txt.setFocusable(false);

        txtInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtInput.setForeground(new java.awt.Color(102, 102, 255));
        txtInput.setBorder(null);

        botoes3.setBackground(new java.awt.Color(51, 51, 255));
        botoes3.setMinimumSize(new java.awt.Dimension(330, 35));
        botoes3.setOpaque(false);

        btnCancelar1.setBackground(new java.awt.Color(245, 71, 71));
        btnCancelar1.setText("Cancelar");
        btnCancelar1.setColorHover(new java.awt.Color(255, 74, 74));
        btnCancelar1.setColorPressed(new java.awt.Color(235, 61, 61));
        btnCancelar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelar1.setMaximumSize(new java.awt.Dimension(163, 35));
        btnCancelar1.setMinimumSize(new java.awt.Dimension(163, 35));
        btnCancelar1.setPreferredSize(new java.awt.Dimension(163, 35));
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnOk1.setText("Ok");
        btnOk1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnOk1.setMaximumSize(new java.awt.Dimension(163, 35));
        btnOk1.setMinimumSize(new java.awt.Dimension(163, 35));
        btnOk1.setPreferredSize(new java.awt.Dimension(163, 35));
        btnOk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout botoes3Layout = new javax.swing.GroupLayout(botoes3);
        botoes3.setLayout(botoes3Layout);
        botoes3Layout.setHorizontalGroup(
            botoes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botoes3Layout.createSequentialGroup()
                .addComponent(btnCancelar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOk1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        botoes3Layout.setVerticalGroup(
            botoes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botoes3Layout.createSequentialGroup()
                .addGroup(botoes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOk1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIcone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt)
                    .addComponent(txtInput)
                    .addComponent(botoes3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIcone)
                .addGap(8, 8, 8)
                .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(botoes3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        texto = txtInput.getText();
        closeMessage();
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        closeMessage();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void init(Icone icone) {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        StyledDocument doc = txt.getStyledDocument();
        SimpleAttributeSet center = new SimpleAttributeSet();
        StyleConstants.setAlignment(center, StyleConstants.ALIGN_CENTER);
        doc.setParagraphAttributes(0, doc.getLength(), center, false);
        txt.setOpaque(false);
        txt.setBackground(new Color(0, 0, 0, 0));
        setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        switch(icone) {
            case INFORMACAO : this.icone = "/icons/info.png";break;
            case SUCESSO    : this.icone = "/icons/sucesso.png";break;
            case AVISO      : this.icone = "/icons/alerta.png";break;
            case QUESTAO    : this.icone = "/icons/pergunta.png";break;
            case ERRO       : this.icone = "/icons/erro.png";break;
        }
        lblIcone.setIcon(new ImageIcon(getClass().getResource(this.icone)));        
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                closeMessage();
            }
        });
        animator = new Animator(350, new TimingTargetAdapter() {
            @Override
            public void timingEvent(float fraction) {
                float f = show ? fraction : 1f - fraction;
                glass.setAlpha(f - f * 0.3f);
                setOpacity(f);
            }

            @Override
            public void end() {
                if (show == false) {
                    dispose();
                    glass.setVisible(false);
                }
            }
        });
        animator.setResolution(0);
        animator.setAcceleration(.5f);
        animator.setDeceleration(.5f);
        setOpacity(0f);
        glass = new Glass();
    }
    
    public static String mostrarDialogoDeIntroducao(JFrame frame, String mensagem, Icone icone) {
        inputDialog = new DialogoEntrada(frame, icone, mensagem);
        
        return getTexto();
    }
    
    private void showMessage(String message) {
        fram.setGlassPane(glass);
        glass.setVisible(true);
        txt.setText(message);
        setLocationRelativeTo(fram);
        startAnimator(true);
        setVisible(true);
    }
    
    private void closeMessage() {
        startAnimator(false);
    }
    
    private static String getTexto() {
        return texto;
    }
    
    private void startAnimator(boolean show) {
        if (animator.isRunning()) {
            float f = animator.getTimingFraction();
            animator.stop();
            animator.setStartFraction(1f - f);
        } else {
            animator.setStartFraction(0f);
        }
        this.show = show;
        animator.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botoes3;
    private view.extras.ButtonCustom btnCancelar1;
    private view.extras.ButtonCustom btnOk1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIcone;
    private javax.swing.JTextPane txt;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables
    private static DialogoEntrada inputDialog;
}
