/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.admin;

import controllerDAO.EmpregadoJpaController;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Empregado;

/**
 *
 * @author helio
 */
public class AdminRegistarForm extends javax.swing.JFrame {

    
    // No formulario DashboardAdmin temos o metedo receber empregado
    private DashboardAdmin enviaEmp; // instancia do classe que se pretende ennviar o obj
    private EmpregadoJpaController empregadoDAO;
    
    /**
     * Creates new form AdminRegistarForm
     */
    public AdminRegistarForm() {
        initComponents();
        this.empregadoDAO = new EmpregadoJpaController(connection.ConnectionFactory.getEmf());
    }
    
    /**
     *  Envia um objecto do tipo Empregado 
     *  para a tela Dashboaradmin
     */
    public void enviaEmpregado(Empregado emp){
        if(enviaEmp == null){
            enviaEmp = new DashboardAdmin();
            enviaEmp.setVisible(true);
            enviaEmp.recebeEmpregado(emp);
        } else {
            enviaEmp.setVisible(true);
            enviaEmp.recebeEmpregado(emp);
        }
    }
    
    /**
     * 
     * @param emp
     * @return 
     */
    private boolean salvarASuperAdmin(Empregado emp){
        try {
            //Salvar od dados no banco de dados
            this.empregadoDAO.create(emp);
            JOptionPane.showMessageDialog(null, "Super Administrador Cadastrado com sucesso! ");
            return true;  // retorne verdadeiro se o funcionario for gravado com sucesso!!
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar o super Administrador");
            e.printStackTrace(); 
            return false; // retorne falso caso o funcionario nao seja gravado!!
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        txtPrimeiroNome = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbxDataNascimento = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        txtApelido = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNuit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbxSexo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        Password = new javax.swing.JLabel();
        ckLembrarPassword = new javax.swing.JCheckBox();
        txtBilheteIdentidade = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtConfirmarPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        rigthRoundedPanel = new view.extras.PanelRound();
        btnContinuar = new com.k33ptoo.components.KButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setPreferredSize(new java.awt.Dimension(1070, 660));

        txtPrimeiroNome.setForeground(new java.awt.Color(102, 102, 102));
        txtPrimeiroNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 202, 202)));

        jLabel13.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Primeiro Nome");

        cbxDataNascimento.setBackground(new java.awt.Color(255, 255, 255));
        cbxDataNascimento.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cbxDataNascimento.setForeground(new java.awt.Color(102, 102, 102));
        cbxDataNascimento.setPreferredSize(new java.awt.Dimension(82, 35));

        jLabel14.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("Data de Nascimento");

        txtApelido.setForeground(new java.awt.Color(102, 102, 102));
        txtApelido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 202, 202)));
        txtApelido.setPreferredSize(new java.awt.Dimension(64, 35));

        jLabel12.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("Apelido");

        txtNuit.setForeground(new java.awt.Color(102, 102, 102));
        txtNuit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 202, 202)));
        txtNuit.setPreferredSize(new java.awt.Dimension(64, 30));
        txtNuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuitActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Nuit");

        txtEmail.setForeground(new java.awt.Color(102, 102, 102));
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 202, 202)));
        txtEmail.setPreferredSize(new java.awt.Dimension(64, 35));

        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Email");

        cbxSexo.setForeground(new java.awt.Color(102, 102, 102));
        cbxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Sexo");

        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 202, 202)));

        Password.setForeground(new java.awt.Color(153, 153, 153));
        Password.setText("Password");

        ckLembrarPassword.setForeground(new java.awt.Color(153, 153, 153));
        ckLembrarPassword.setText("Lembrar a Pass-word");
        ckLembrarPassword.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ckLembrarPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckLembrarPasswordActionPerformed(evt);
            }
        });

        txtBilheteIdentidade.setForeground(new java.awt.Color(102, 102, 102));
        txtBilheteIdentidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 202, 202)));

        jLabel11.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Bilhete e Identidade");

        txtConfirmarPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 202, 202)));

        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Confirmar Password");

        rigthRoundedPanel.setBackground(new java.awt.Color(229, 85, 85));
        rigthRoundedPanel.setRoundBottomLeft(60);
        rigthRoundedPanel.setRoundBottomRight(60);
        rigthRoundedPanel.setRoundTopLeft(60);
        rigthRoundedPanel.setRoundTopRight(60);

        javax.swing.GroupLayout rigthRoundedPanelLayout = new javax.swing.GroupLayout(rigthRoundedPanel);
        rigthRoundedPanel.setLayout(rigthRoundedPanelLayout);
        rigthRoundedPanelLayout.setHorizontalGroup(
            rigthRoundedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );
        rigthRoundedPanelLayout.setVerticalGroup(
            rigthRoundedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnContinuar.setText("Continuar");
        btnContinuar.setkBorderRadius(30);
        btnContinuar.setkEndColor(new java.awt.Color(44, 44, 57));
        btnContinuar.setkHoverEndColor(new java.awt.Color(51, 51, 51));
        btnContinuar.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnContinuar.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        btnContinuar.setkStartColor(new java.awt.Color(44, 44, 57));
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Crie a sua conta super administrador");

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel2.setText("Bem Vindo!");

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                                        .addComponent(txtBilheteIdentidade)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNuit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(MainPanelLayout.createSequentialGroup()
                                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(ckLembrarPassword)
                                                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(MainPanelLayout.createSequentialGroup()
                                                            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel14)
                                                                .addComponent(cbxDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGap(35, 35, 35)
                                                            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel8)
                                                                .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(Password, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtConfirmarPassword, javax.swing.GroupLayout.Alignment.LEADING))))
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MainPanelLayout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addComponent(txtPrimeiroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(MainPanelLayout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(jLabel13)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(txtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(56, 56, 56))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(187, 187, 187)))
                .addComponent(rigthRoundedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(38, 38, 38)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addGap(0, 0, 0)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrimeiroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel5))
                .addGap(0, 0, 0)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBilheteIdentidade, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNuit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jLabel7)
                .addGap(0, 0, 0)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, 0)
                        .addComponent(cbxDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, 0)
                        .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Password)
                .addGap(1, 1, 1)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(txtConfirmarPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckLembrarPassword)
                .addGap(30, 30, 30)
                .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rigthRoundedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1057, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuitActionPerformed

    private void ckLembrarPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckLembrarPasswordActionPerformed
      // O metedo isSelected verifica se o checkbox foi selecionado ou não
        // Verificar se o checkbox foi selecionado,
        // se tiver sido selecionado mostrar a senha caso não ocultar
        if(ckLembrarPassword.isSelected()){
            txtPassword.setEchoChar((char)0);
            txtConfirmarPassword.setEchoChar((char)0);
        }else{
            txtPassword.setEchoChar('*');
            txtConfirmarPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_ckLembrarPasswordActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        // TODO add your handling code here:
        
        Empregado emp = new Empregado();
        Date date = new Date(System.currentTimeMillis());  
        String sexo = String.valueOf(cbxSexo.getSelectedItem());
        
        emp.setPrimeiroNome(txtPrimeiroNome.getText());
        emp.setApelido(txtApelido.getText());
        emp.setPrimeiroNome(txtPrimeiroNome.getText());
        emp.setBilheteIdentidade(txtBilheteIdentidade.getText());
        emp.setEmail(txtEmail.getText());
        emp.setNuit(txtNuit.getText());
        emp.setDataCadastro(date);
        emp.setDataNascimento(cbxDataNascimento.getDate());
        emp.setSexo(sexo.charAt(0));    // Converter uma string "M" em um char 'M'
        emp.setNivelDeAcesso(0);  // O Nivel de Acesso '0' coresponde ao SuperAdmin
        emp.setFuncao("Super Admin");  // dar por Deafault a funcao super admin
        //Gerar uma nova senha Aleatoria Para Ca registo.
        
        if(txtPassword.getText().equals(txtConfirmarPassword.getText())){
            emp.setSenha(txtConfirmarPassword.getText());  
            if(salvarASuperAdmin(emp)){
                // Envia um empregado para outra classe!!
                enviaEmpregado(emp);
                this.dispose();
                //DashboardAdmin dashboardAmin = new DashboardAdmin();
                //dashboardAmin.setVisible(true);
            }
        } else{
            JOptionPane.showMessageDialog(this, "Confirmar a sua Senha, as Senhas sao diferentes!!");
        } 
    }//GEN-LAST:event_btnContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminRegistarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminRegistarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminRegistarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminRegistarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminRegistarForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel Password;
    private com.k33ptoo.components.KButton btnContinuar;
    private com.toedter.calendar.JDateChooser cbxDataNascimento;
    private javax.swing.JComboBox<String> cbxSexo;
    private javax.swing.JCheckBox ckLembrarPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private view.extras.PanelRound rigthRoundedPanel;
    private javax.swing.JTextField txtApelido;
    private javax.swing.JTextField txtBilheteIdentidade;
    private javax.swing.JPasswordField txtConfirmarPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNuit;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPrimeiroNome;
    // End of variables declaration//GEN-END:variables
}
