package view.login.forms;

import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author helio
 */
public class ResetPasswordForm extends javax.swing.JDialog {

    /**
     * Creates new form ResetPasswordForm
     */
    public ResetPasswordForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void showPanel(JPanel jpanel){
        containerPanel.removeAll();
        containerPanel.repaint();
        containerPanel.revalidate();
        containerPanel.add(jpanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backGroundPanel = new javax.swing.JPanel();
        MenuFixedPanel = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JLabel();
        containerPanel = new javax.swing.JPanel();
        VerifictionCodePanel = new javax.swing.JPanel();
        btnContinuarCodigo = new com.k33ptoo.components.KButton();
        txtEmailCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCodigoVerificacao = new com.k33ptoo.components.KButton();
        resetPasswordPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtPassWord = new javax.swing.JPasswordField();
        txtConfirmarPassWord3 = new javax.swing.JPasswordField();
        ckLembrarPassword = new javax.swing.JCheckBox();
        txtEmail2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tbnIniciarSessaao2 = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        backGroundPanel.setBackground(new java.awt.Color(255, 255, 255));

        MenuFixedPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnCancelar.setForeground(new java.awt.Color(102, 102, 102));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons_back.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MenuFixedPanelLayout = new javax.swing.GroupLayout(MenuFixedPanel);
        MenuFixedPanel.setLayout(MenuFixedPanelLayout);
        MenuFixedPanelLayout.setHorizontalGroup(
            MenuFixedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuFixedPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuFixedPanelLayout.setVerticalGroup(
            MenuFixedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuFixedPanelLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(17, 17, 17))
        );

        containerPanel.setLayout(new java.awt.CardLayout());

        VerifictionCodePanel.setBackground(new java.awt.Color(255, 255, 255));

        btnContinuarCodigo.setText("Continuar");
        btnContinuarCodigo.setkEndColor(new java.awt.Color(44, 44, 57));
        btnContinuarCodigo.setkHoverEndColor(new java.awt.Color(51, 51, 51));
        btnContinuarCodigo.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnContinuarCodigo.setkHoverStartColor(new java.awt.Color(68, 146, 70));
        btnContinuarCodigo.setkStartColor(new java.awt.Color(68, 146, 70));
        btnContinuarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarCodigoActionPerformed(evt);
            }
        });

        txtEmailCodigo.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        txtEmailCodigo.setText("  Introduz o email");
        txtEmailCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 202, 202)));
        txtEmailCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailCodigoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setText("Detalhes do usuario");

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Introduza o Email da conta a recuperar a senha");

        btnCodigoVerificacao.setText("enviar código de verificação");
        btnCodigoVerificacao.setkEndColor(new java.awt.Color(44, 44, 57));
        btnCodigoVerificacao.setkHoverEndColor(new java.awt.Color(51, 51, 51));
        btnCodigoVerificacao.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnCodigoVerificacao.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        btnCodigoVerificacao.setkStartColor(new java.awt.Color(44, 44, 57));
        btnCodigoVerificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodigoVerificacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VerifictionCodePanelLayout = new javax.swing.GroupLayout(VerifictionCodePanel);
        VerifictionCodePanel.setLayout(VerifictionCodePanelLayout);
        VerifictionCodePanelLayout.setHorizontalGroup(
            VerifictionCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VerifictionCodePanelLayout.createSequentialGroup()
                .addGroup(VerifictionCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VerifictionCodePanelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(VerifictionCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCodigoVerificacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnContinuarCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(txtEmailCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)))
                    .addGroup(VerifictionCodePanelLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1))
                    .addGroup(VerifictionCodePanelLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel3)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        VerifictionCodePanelLayout.setVerticalGroup(
            VerifictionCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VerifictionCodePanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(46, 46, 46)
                .addComponent(txtEmailCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCodigoVerificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnContinuarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        containerPanel.add(VerifictionCodePanel, "card2");

        resetPasswordPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel2.setText("Detalhes do usuario");

        txtPassWord.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        txtPassWord.setText(" introduz a password");
        txtPassWord.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 202, 202)));

        txtConfirmarPassWord3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        txtConfirmarPassWord3.setText(" Confirma a sua password");
        txtConfirmarPassWord3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 202, 202)));
        txtConfirmarPassWord3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfirmarPassWord3ActionPerformed(evt);
            }
        });

        ckLembrarPassword.setForeground(new java.awt.Color(153, 153, 153));
        ckLembrarPassword.setText("Lembrar a Password");
        ckLembrarPassword.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        txtEmail2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        txtEmail2.setText("codigo de verificação");
        txtEmail2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 202, 202)));

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Introduza o codigo de verificação enviado por email");

        tbnIniciarSessaao2.setText("Continuar");
        tbnIniciarSessaao2.setkEndColor(new java.awt.Color(44, 44, 57));
        tbnIniciarSessaao2.setkHoverEndColor(new java.awt.Color(51, 51, 51));
        tbnIniciarSessaao2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        tbnIniciarSessaao2.setkHoverStartColor(new java.awt.Color(68, 146, 70));
        tbnIniciarSessaao2.setkStartColor(new java.awt.Color(68, 146, 70));
        tbnIniciarSessaao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnIniciarSessaao2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout resetPasswordPanelLayout = new javax.swing.GroupLayout(resetPasswordPanel);
        resetPasswordPanel.setLayout(resetPasswordPanelLayout);
        resetPasswordPanelLayout.setHorizontalGroup(
            resetPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resetPasswordPanelLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(resetPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(resetPasswordPanelLayout.createSequentialGroup()
                        .addGroup(resetPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(ckLembrarPassword)
                            .addComponent(txtPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(86, Short.MAX_VALUE))
                    .addGroup(resetPasswordPanelLayout.createSequentialGroup()
                        .addGroup(resetPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtConfirmarPassWord3)
                            .addComponent(tbnIniciarSessaao2, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(resetPasswordPanelLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        resetPasswordPanelLayout.setVerticalGroup(
            resetPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resetPasswordPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(25, 25, 25)
                .addComponent(txtEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(txtConfirmarPassWord3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckLembrarPassword)
                .addGap(18, 18, 18)
                .addComponent(tbnIniciarSessaao2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        containerPanel.add(resetPasswordPanel, "card3");

        javax.swing.GroupLayout backGroundPanelLayout = new javax.swing.GroupLayout(backGroundPanel);
        backGroundPanel.setLayout(backGroundPanelLayout);
        backGroundPanelLayout.setHorizontalGroup(
            backGroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuFixedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        backGroundPanelLayout.setVerticalGroup(
            backGroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backGroundPanelLayout.createSequentialGroup()
                .addComponent(MenuFixedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backGroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backGroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarCodigoActionPerformed
        // TODO add your handling code here:
        
        // Chamar o painel para fazer o reset da password!
        showPanel(resetPasswordPanel);
    }//GEN-LAST:event_btnContinuarCodigoActionPerformed

    private void txtEmailCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailCodigoActionPerformed

    private void btnCodigoVerificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodigoVerificacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCodigoVerificacaoActionPerformed

    private void txtConfirmarPassWord3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmarPassWord3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmarPassWord3ActionPerformed

    private void tbnIniciarSessaao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnIniciarSessaao2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbnIniciarSessaao2ActionPerformed

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        // TODO add your handling code here:
        
        // chamar a tela para enviar o codigo de verificação
        // o metedo isDisplayable verifica se o componete ista a ser exibido!!
        if(resetPasswordPanel.isDisplayable()){    
            showPanel(VerifictionCodePanel);
            System.out.println("O panel resetPasswordPanel esta visivel");
        }else{    
            System.out.println("O Panel resetPasswordPane não esta visivel");
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResetPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResetPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResetPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResetPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ResetPasswordForm dialog = new ResetPasswordForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuFixedPanel;
    private javax.swing.JPanel VerifictionCodePanel;
    private javax.swing.JPanel backGroundPanel;
    private javax.swing.JLabel btnCancelar;
    private com.k33ptoo.components.KButton btnCodigoVerificacao;
    private com.k33ptoo.components.KButton btnContinuarCodigo;
    private javax.swing.JCheckBox ckLembrarPassword;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel resetPasswordPanel;
    private com.k33ptoo.components.KButton tbnIniciarSessaao2;
    private javax.swing.JPasswordField txtConfirmarPassWord3;
    private javax.swing.JTextField txtEmail2;
    private javax.swing.JTextField txtEmailCodigo;
    private javax.swing.JPasswordField txtPassWord;
    // End of variables declaration//GEN-END:variables
}
